title: afaundez
email: alvaro@faundez.net
description: >-
  My stuff
baseurl: ""
url: https://alvaro.faundez.net
twitter_username: afaundez
github_username: afaundez

github: [metadata]

source: _source

favicon:
  path: /assets/img/favicon
  apple-touch-icon:
    background: '#f1904e'
  safari-pinned-tab:
    mask-icon-color: '#f1904e'
  ie:
    tile-color: '#f1904e'
