title: afaundez
email: alvaro@faundez.net
description: >-
  My stuff
baseurl: ""
url: https://alvaro.faundez.net
twitter_username: afaundez
github_username: afaundez
markdown: kramdown
exclude:
  - .git
  - .gitignore
  - .ruby-version
  - CNAME
  - favicon.svg
  - Gemfile
  - Gemfile.lock
  - README.md
keep_files:
  - assets/data
  - assets/media
  - assets/posts
theme: minima
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: post
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: page
