title: afaundez
email: alvaro@faundez.net
description: >-
  My stuff
baseurl: ""
url: https://alvaro.faundez.net
twitter_username: afaundez
github_username: afaundez

github: [metadata]

source: source
exclude:
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock
