title: afaundez
email: alvaro@faundez.net
description: >-
  My stuff
baseurl: ""
url: https://alvaro.faundez.net
twitter_username: afaundez
github_username: afaundez

theme: false
exclude:
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - favicon.svg

# favicon:
#   path: /assets/media/favicon
#   apple-touch-icon:
#     background: '#f1904e'
#   safari-pinned-tab:
#     mask-icon-color: '#f1904e'
#   ie:
#     tile-color: '#f1904e'
